
[[Snippets]]
  Description = "Print all bash shell options"
  Output = ""
  Tag = []
  command = "shopt -p"

[[Snippets]]
  Description = "Recursively delete .DS_Store files"
  Output = ""
  Tag = []
  command = "find . -name '.DS_Store' -type f -delete"

[[Snippets]]
  Description = "sudo killall -HUP mDNSResponder; sleep 2;"
  Output = ""
  Tag = []
  command = "Clear DNS cache"

[[Snippets]]
  Description = "Start vim with default settings and nocompatible"
  Output = ""
  Tag = []
  command = "vim -u NONE -N"

[[Snippets]]
  Description = "Set a bash option with shopt"
  Output = ""
  Tag = []
  command = "shopt -s extglob"

[[Snippets]]
  Description = "List standard I/O device files for stdin, stdout, stderr"
  Output = ""
  Tag = []
  command = "lsof -a -p $$ -d0,1,2"

[[Snippets]]
  Description = "echo terminal emulator type"
  Output = ""
  Tag = []
  command = "echo $TERM"

[[Snippets]]
  Description = "List bash builtins"
  Output = ""
  Tag = []
  command = "compgen -b"

[[Snippets]]
  Description = "Save to file list of tty processes with environment variables"
  Output = ""
  Tag = []
  command = "ps -TE > ~/Desktop/ps-with-env.txt"

[[Snippets]]
  Description = "Get battery capacity"
  Output = ""
  Tag = []
  command = "ioreg -w 0 -f -r -c AppleSmartBattery | grep \"DesignCapacity\""

[[Snippets]]
  Description = "Get Azure subscriptions"
  Output = ""
  Tag = []
  command = "az account list"

[[Snippets]]
  Description = "Rename master branch to main"
  Output = ""
  Tag = []
  command = "git branch -m master main"

[[Snippets]]
  Description = "Show git remote tracking branch"
  Output = ""
  Tag = []
  command = "git status -sb"

[[Snippets]]
  Description = "Print Unix timestamp as local ref822 datetime string"
  Output = ""
  Tag = []
  command = "date -r <unix_timestamp=`date +%s`>"

[[Snippets]]
  Description = "Print Unix timestamp as UTC ref822 datetime string"
  Output = ""
  Tag = []
  command = "date -u -r <unix_timestamp=`date +%s`>"

[[Snippets]]
  Description = "Print Unix timestamp"
  Output = ""
  Tag = []
  command = "date +%s"

[[Snippets]]
  Description = "Print HTTP response headers with curl"
  Output = ""
  Tag = []
  command = "curl -s -o /dev/null -D - <url>"

[[Snippets]]
  Description = "Print HTTP headers matching grep pattern using curl"
  Output = ""
  Tag = []
  command = "curl -s <url> -I | grep -Fi <header=Content-Type>"

[[Snippets]]
  Description = "Print HTTP request headers using curl"
  Output = ""
  Tag = []
  command = "curl -vso /dev/null <url> 2>&1 | __char1='>' sed '/^[* {}<]/d; s/'$__char1' //;'"

[[Snippets]]
  Description = "Count number of files in directory"
  Output = ""
  Tag = []
  command = "find -type f | wc -l"

[[Snippets]]
  Description = "List files changed since <sha>"
  Output = ""
  Tag = []
  command = "git diff-tree --no-commit-id --name-only -r <sha=HEAD>"

[[Snippets]]
  Description = "Delete my Arc preferences"
  Output = ""
  Tag = []
  command = "curl -X DELETE --header 'Accept: */*' --header 'X-IDENTITY:  5098b9ec-40d9-453a-b35d-65f07ef2a6b6@identity' --header 'X-DWA-TOKEN: eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTExNjAxMzE5NDQsImlzcyI6ImF1dGhuLzIiLCJleHAiOjE2NTExNjM3MzE5NDQsIm5hbWUiOiJKb2huIExveSIsImlwIjoiMTkyLjE2OC4xODAuMjQwIiwiZG9tYWlucyI6W10sInN1YiI6ImpvaG4ubG95QGRyZWFtd29ya3MuY29tIiwiaWRlbnRpdHkiOiI1MDk4YjllYy00MGQ5LTQ1M2EtYjM1ZC02NWYwN2VmMmE2YjZAaWRlbnRpdHkiLCJjYXBhYmlsaXRpZXMiOltdfQ.Fh3N_JAeuf-gJmLXtFNFIn9z9gW6DoeboI0FPrvSZ-M' 'http://studio.svc.gld.dreamworks.net/pam/config/1/serve/pipeline/arc-1/sessions/5098b9ec-40d9-453a-b35d-65f07ef2a6b6@identity'"

[[Snippets]]
  Description = "Get the current user's default shell"
  Output = ""
  Tag = []
  command = "dscl . -read /Users/$USER UserShell"
