# Common interactive profile for bash, zsh, ksh, and other bourne-derived shells
[ -e ~/.profile ] && source ~/.profile

# Ensure that the shims directory is in the PATH
export PATH="${HOME}/.local/share/mise/shims:${PATH}"

source "${DOTFILES_DIR}/bash/env.sh"
source "${DOTFILES_DIR}/bash/functions.sh"
source "${DOTFILES_DIR}/bash/aliases.sh"
source "${DOTFILES_DIR}/bash/completions.sh"

eval "$(mise activate bash --shims)"
eval "$(starship init bash)"

[ -s ~/.bashrc_local ] && source ~/.bashrc_local
